import type { Person, Message } from "./types";

export const mockPeople: Person[] = [
  {
    id: "1",
    name: "Alice Johnson",
    email: "alice@example.com",
    role: "Product Designer",
    company: "Figma",
    label: "blue",
    labelText: "Design",
    starred: true,
    unread: true,
    initials: "AJ",
    lastContact: "10:30 AM",
    snippet: "Here are the updated design specs for review.",
  },
  {
    id: "2",
    name: "Bob Martinez",
    email: "bob@startup.io",
    role: "Backend Engineer",
    company: "Startup.io",
    label: "green",
    labelText: "Engineering",
    starred: false,
    unread: false,
    initials: "BM",
    lastContact: "Yesterday",
    snippet: "The API endpoints are now live in staging.",
  },
  {
    id: "3",
    name: "Carol Smith",
    email: "carol@agency.co",
    role: "Marketing Lead",
    company: "Agency Co.",
    label: "yellow",
    labelText: "Marketing",
    starred: false,
    unread: true,
    initials: "CS",
    lastContact: "May 18",
    snippet: "Campaign results exceeded Q2 targets by 23%.",
  },
  {
    id: "4",
    name: "David Kim",
    email: "david@corp.com",
    role: "VP of Sales",
    company: "Corp Inc.",
    label: "red",
    labelText: "Sales",
    starred: true,
    unread: false,
    initials: "DK",
    lastContact: "May 15",
    snippet: "Closing the enterprise deal next Friday.",
  },
  {
    id: "5",
    name: "Eva Chen",
    email: "eva@labs.dev",
    role: "ML Engineer",
    company: "Labs Dev",
    label: "blue",
    labelText: "Research",
    starred: false,
    unread: true,
    initials: "EC",
    lastContact: "May 12",
    snippet: "The new model achieves 94% accuracy on the benchmark.",
  },
  {
    id: "6",
    name: "Frank Lee",
    email: "frank@consultancy.biz",
    role: "Strategy Consultant",
    company: "Consultancy Biz",
    label: "green",
    labelText: "Strategy",
    starred: false,
    unread: false,
    initials: "FL",
    lastContact: "May 10",
    snippet: "Roadmap for Q3 has been approved by the board.",
  },
];

export const mockMessages: Message[] = [
  {
    id: "m1",
    from: "Alice Johnson",
    fromInitials: "AJ",
    to: "me@example.com",
    subject: "Updated Design Specs",
    snippet: "Here are the updated design specs for review.",
    body: "Hi,\n\nI have attached the updated design specs for the new dashboard. Please review and let me know if any changes are needed.\n\nBest,\nAlice",
    timestamp: "10:30 AM",
    unread: true,
    starred: true,
    label: "blue",
    labelText: "Design",
  },
  {
    id: "m2",
    from: "Bob Martinez",
    fromInitials: "BM",
    to: "me@example.com",
    subject: "API Staging Deployment",
    snippet: "The API endpoints are now live in staging.",
    body: "The API is deployed to staging. Run the integration tests and let me know if you find any issues.",
    timestamp: "Yesterday",
    unread: false,
    starred: false,
    label: "green",
    labelText: "Engineering",
  },
  {
    id: "m3",
    from: "Carol Smith",
    fromInitials: "CS",
    to: "me@example.com",
    subject: "Q2 Campaign Results",
    snippet: "Campaign results exceeded Q2 targets by 23%.",
    body: "Great news! The Q2 marketing campaign exceeded all targets. Full report attached.",
    timestamp: "May 18",
    unread: true,
    starred: false,
    label: "yellow",
    labelText: "Marketing",
  },
  {
    id: "m4",
    from: "David Kim",
    fromInitials: "DK",
    to: "me@example.com",
    subject: "Enterprise Deal Update",
    snippet: "Closing the enterprise deal next Friday.",
    body: "We are on track to close the deal. The legal team has signed off on the terms.",
    timestamp: "May 15",
    unread: false,
    starred: true,
    label: "red",
    labelText: "Sales",
  },
  {
    id: "m5",
    from: "Eva Chen",
    fromInitials: "EC",
    to: "me@example.com",
    subject: "Model Benchmark Results",
    snippet: "The new model achieves 94% accuracy on the benchmark.",
    body: "Sharing the benchmark results from last week's experiments. The performance is significantly better.",
    timestamp: "May 12",
    unread: true,
    starred: false,
    label: "blue",
    labelText: "Research",
  },
  {
    id: "m6",
    from: "Frank Lee",
    fromInitials: "FL",
    to: "me@example.com",
    subject: "Q3 Roadmap Approved",
    snippet: "Roadmap for Q3 has been approved by the board.",
    body: "The board approved the Q3 strategic roadmap yesterday. Execution begins June 1.",
    timestamp: "May 10",
    unread: false,
    starred: false,
    label: "green",
    labelText: "Strategy",
  },
  {
    id: "m7",
    from: "Alice Johnson",
    fromInitials: "AJ",
    to: "me@example.com",
    subject: "Component Library Update",
    snippet: "New icon set and token updates are live.",
    body: "The component library has been updated with the new icon set and design tokens. Changelog attached.",
    timestamp: "May 8",
    unread: false,
    starred: false,
  },
  {
    id: "m8",
    from: "Bob Martinez",
    fromInitials: "BM",
    to: "me@example.com",
    subject: "Database Migration Plan",
    snippet: "Migration scheduled for Saturday 2 AM UTC.",
    body: "We will migrate the production database this Saturday. Downtime expected: 15 minutes.",
    timestamp: "May 6",
    unread: false,
    starred: false,
    label: "green",
    labelText: "Engineering",
  },
];

export const mockSnoozedMessages: Message[] = [
  {
    id: "s1",
    from: "Grace Liu",
    fromInitials: "GL",
    to: "me@example.com",
    subject: "Budget Review Meeting",
    snippet: "Rescheduled for next Monday at 2 PM.",
    body: "The budget review meeting has been rescheduled. Please update your calendar accordingly.",
    timestamp: "Tomorrow",
    unread: false,
    starred: false,
    label: "yellow",
    labelText: "Finance",
  },
  {
    id: "s2",
    from: "Henry Wang",
    fromInitials: "HW",
    to: "me@example.com",
    subject: "Performance Review",
    snippet: "Q2 review scheduled for next week.",
    body: "Your Q2 performance review is scheduled for next Thursday. Please prepare your self-assessment.",
    timestamp: "May 20",
    unread: false,
    starred: false,
    label: "blue",
    labelText: "HR",
  },
];

export const mockDraftMessages: Message[] = [
  {
    id: "d1",
    from: "me@example.com",
    fromInitials: "ME",
    to: "team@company.com",
    subject: "Weekly Update - Week 20",
    snippet: "Draft: Progress on key deliverables...",
    body: "Team,\n\nHere's our weekly update for Week 20:\n\n1. Project Alpha: On track\n2. Project Beta: Delayed by 2 days\n3. Project Gamma: Completed\n\n[Draft - not sent]",
    timestamp: "Draft",
    unread: false,
    starred: false,
  },
  {
    id: "d2",
    from: "me@example.com",
    fromInitials: "ME",
    to: "client@external.com",
    subject: "Proposal for Phase 2",
    snippet: "Draft: Attached is the revised proposal...",
    body: "Dear Client,\n\nPlease find attached the revised proposal for Phase 2 of our engagement. We've incorporated your feedback from the last call.\n\n[Draft - not sent]",
    timestamp: "Draft",
    unread: false,
    starred: false,
  },
];
